#!/bin/sh
# Print the Homebrew formula for a published release. It is written from the
# release's checksums.txt only after that file's signature verifies against
# the Cintelis release key: Homebrew itself checks only the sha256 in the
# formula, so the formula must come from checksums we've verified.
#
#   scripts/brew-formula.sh v1.2.3 > Formula/cintelis.rb
#
# sign-release.sh runs this after publishing. Needs: gh, ssh-keygen.
set -eu

REPO="cintelis/hackernews"
NS="cintelis-release"
tag="${1:?usage: scripts/brew-formula.sh vX.Y.Z}"
version="${tag#v}"
root=$(cd "$(dirname "$0")/.." && pwd)
pub="$root/internal/update/release_key.pub"

tmp=$(mktemp -d)
trap 'rm -rf "$tmp"' EXIT
gh release download "$tag" -R "$REPO" -D "$tmp" -p checksums.txt -p checksums.txt.sig
printf '%s namespaces="%s" %s\n' "$NS" "$NS" "$(cut -d' ' -f1,2 "$pub")" > "$tmp/allowed_signers"
if ! ssh-keygen -Y verify -f "$tmp/allowed_signers" -I "$NS" -n "$NS" \
  -s "$tmp/checksums.txt.sig" < "$tmp/checksums.txt" >/dev/null 2>&1; then
  echo "$tag: checksums.txt isn't signed with the Cintelis release key" >&2
  exit 1
fi

sum() {
  s=$(awk -v f="cintelis_${version}_$1.tar.gz" '$2 == f { print $1 }' "$tmp/checksums.txt")
  [ -n "$s" ] || { echo "$tag has no $1 archive" >&2; exit 1; }
  echo "$s"
}
darwin_arm64=$(sum darwin_arm64)
darwin_amd64=$(sum darwin_amd64)
linux_arm64=$(sum linux_arm64)
linux_amd64=$(sum linux_amd64)
base="https://github.com/$REPO/releases/download/$tag"

cat <<EOF
# Generated by scripts/brew-formula.sh in cintelis/hackernews from the
# checksums of $tag, after verifying their signature with the Cintelis
# release key. Don't edit by hand: the next release replaces it.
class Cintelis < Formula
  desc "CISO AI - Hacker News: a fast Hacker News reader for the terminal"
  homepage "https://github.com/cintelis/hackernews"
  version "$version"
  license "MIT"

  on_macos do
    on_arm do
      url "$base/cintelis_${version}_darwin_arm64.tar.gz"
      sha256 "$darwin_arm64"
    end
    on_intel do
      url "$base/cintelis_${version}_darwin_amd64.tar.gz"
      sha256 "$darwin_amd64"
    end
  end

  on_linux do
    on_arm do
      url "$base/cintelis_${version}_linux_arm64.tar.gz"
      sha256 "$linux_arm64"
    end
    on_intel do
      url "$base/cintelis_${version}_linux_amd64.tar.gz"
      sha256 "$linux_amd64"
    end
  end

  def install
    bin.install "cintelis"
  end

  test do
    assert_match "cintelis #{version}", shell_output("#{bin}/cintelis version")
  end
end
EOF
