#!/bin/sh
# Rebuild the README's release table from GitHub's record of published
# releases, checking each release's signature against the committed release
# key as it goes — a row only says "verified" if it just was.
#
#   scripts/release-table.sh        # rewrites README.md in place
#
# sign-release.sh runs this after publishing. Needs: gh, ssh-keygen.
set -eu

REPO="cintelis/hackernews"
NS="cintelis-release"
root=$(cd "$(dirname "$0")/.." && pwd)
readme="$root/README.md"
pub="$root/internal/update/release_key.pub"

tmp=$(mktemp -d)
trap 'rm -rf "$tmp"' EXIT
printf '%s namespaces="%s" %s\n' "$NS" "$NS" "$(cut -d' ' -f1,2 "$pub")" > "$tmp/allowed_signers"
fingerprint=$(ssh-keygen -lf "$pub" | cut -d' ' -f2)

{
  echo "| Release | Published | Checksums | Signature | Signature check | Build |"
  echo "| --- | --- | --- | --- | --- | --- |"
  for tag in $(gh release list -R "$REPO" --exclude-drafts --limit 200 --json tagName --jq '.[].tagName'); do
    base="https://github.com/$REPO/releases/download/$tag"
    published=$(gh release view "$tag" -R "$REPO" --json publishedAt --jq '.publishedAt[0:10]')
    rm -f "$tmp/checksums.txt" "$tmp/checksums.txt.sig"
    check="❌ unsigned"
    if gh release download "$tag" -R "$REPO" -D "$tmp" -p checksums.txt -p checksums.txt.sig 2>/dev/null; then
      if ssh-keygen -Y verify -f "$tmp/allowed_signers" -I "$NS" -n "$NS" \
        -s "$tmp/checksums.txt.sig" < "$tmp/checksums.txt" >/dev/null 2>&1; then
        check="✅ release key"
      else
        check="❌ bad signature"
      fi
    fi
    run=$(gh run list -R "$REPO" --workflow Release --limit 200 --json headBranch,url \
      --jq ".[] | select(.headBranch == \"$tag\") | .url" | head -n 1)
    build="—"
    [ -n "$run" ] && build="[workflow run]($run)"
    echo "| [$tag](https://github.com/$REPO/releases/tag/$tag) | $published | [checksums.txt]($base/checksums.txt) | [checksums.txt.sig]($base/checksums.txt.sig) | $check | $build |"
  done
  echo
  echo "Signature check: \`checksums.txt.sig\` verified against the release key (\`$fingerprint\`)"
  echo "when this table was generated by \`scripts/release-table.sh\`. To check a download"
  echo "yourself, see [SECURITY.md](SECURITY.md#verifying-a-release-yourself)."
} > "$tmp/table.md"

# replace everything between the markers, keeping the markers
awk -v table="$tmp/table.md" '
  /<!-- releases:start -->/ { print; while ((getline line < table) > 0) print line; skip = 1; next }
  /<!-- releases:end -->/   { skip = 0 }
  !skip
' "$readme" > "$tmp/README.md"
grep -q "<!-- releases:end -->" "$tmp/README.md" || { echo "README.md has no release markers" >&2; exit 1; }
cp "$tmp/README.md" "$readme"
echo "release table updated in README.md"
