#!/bin/sh
# Sign and publish a release. The release workflow builds each tag into a
# DRAFT; nothing is installable until this signs it, with a key that never
# leaves the maintainer's machine:
#
#   scripts/sign-release.sh v1.2.3 [path/to/private/key]
#
# It checks the draft first — every archive was built by this repo's release
# workflow (build attestation) and matches checksums.txt — then signs
# checksums.txt, verifies the signature against the key committed in
# internal/update/release_key.pub, uploads it and publishes the release.
# Needs: gh (logged in), ssh-keygen (OpenSSH 8.1+), sha256sum or shasum.
set -eu

REPO="cintelis/hackernews"
TAP="cintelis/homebrew-tap"
NS="cintelis-release"
tag="${1:?usage: scripts/sign-release.sh vX.Y.Z [private key]}"
key="${2:-$HOME/.ssh/cintelis-release}"
root=$(cd "$(dirname "$0")/.." && pwd)
pub="$root/internal/update/release_key.pub"

[ -f "$key" ] || { echo "no private key at $key" >&2; exit 1; }
# the release-table PR at the end is pushed with gh's active account: check
# it can write here before anything is signed or published
who=$(gh api user --jq .login)
for r in "$REPO" "$TAP"; do
  if [ "$(gh api "repos/$r" --jq .permissions.push)" != "true" ]; then
    echo "gh is logged in as $who, which can't push to $r." >&2
    echo "Switch to an account that can: gh auth switch --user <account>" >&2
    exit 1
  fi
done
if [ "$(gh release view "$tag" -R "$REPO" --json isDraft --jq .isDraft)" != "true" ]; then
  echo "$tag is not a draft release (already published, or not built yet)" >&2
  exit 1
fi

tmp=$(mktemp -d)
trap 'rm -rf "$tmp"' EXIT
gh release download "$tag" -R "$REPO" -D "$tmp"

echo "checking build provenance ..."
for f in "$tmp"/*.tar.gz "$tmp"/*.zip; do
  gh attestation verify "$f" -R "$REPO" >/dev/null
done

echo "checking checksums ..."
if command -v sha256sum >/dev/null 2>&1; then
  (cd "$tmp" && sha256sum -c --quiet checksums.txt)
else
  (cd "$tmp" && shasum -a 256 -c --quiet checksums.txt)
fi

echo "signing checksums.txt ..."
rm -f "$tmp/checksums.txt.sig"
ssh-keygen -Y sign -f "$key" -n "$NS" "$tmp/checksums.txt"

# the signature must verify with the key the app and installers carry
printf '%s namespaces="%s" %s\n' "$NS" "$NS" "$(cut -d' ' -f1,2 "$pub")" > "$tmp/allowed_signers"
ssh-keygen -Y verify -f "$tmp/allowed_signers" -I "$NS" -n "$NS" \
  -s "$tmp/checksums.txt.sig" < "$tmp/checksums.txt"

# --clobber: a rerun after a failed publish replaces the signature it uploaded
# (the release is still a draft, so it can change; once published it can't)
gh release upload "$tag" "$tmp/checksums.txt.sig" -R "$REPO" --clobber
gh release edit "$tag" -R "$REPO" --draft=false --latest
echo "published $tag"

# Homebrew: the tap's formula, written from the checksums just signed (it
# re-verifies them). Homebrew checks only the formula's sha256s, so the
# formula comes from here, never from CI.
git clone -q "https://github.com/$TAP.git" "$tmp/tap"
mkdir -p "$tmp/tap/Formula"
"$root/scripts/brew-formula.sh" "$tag" > "$tmp/tap/Formula/cintelis.rb"
git -C "$tmp/tap" add Formula/cintelis.rb
git -C "$tmp/tap" commit -q -m "cintelis $tag"
git -C "$tmp/tap" push -q origin HEAD
echo "Homebrew formula updated to $tag (brew upgrade cintelis)"

# Record it in the README's release table: a PR that merges itself once CI
# passes. Skipped (with a note) if the checkout has uncommitted work.
if [ -n "$(git -C "$root" status --porcelain)" ]; then
  echo "note: uncommitted changes here, so the release table wasn't updated —" >&2
  echo "      run scripts/release-table.sh on a clean branch and open a PR" >&2
  exit 0
fi
back=$(git -C "$root" branch --show-current)
branch="docs/release-table-$tag"
git -C "$root" fetch -q origin main
git -C "$root" switch -q -c "$branch" origin/main
"$root/scripts/release-table.sh"
git -C "$root" commit -q -am "docs: add $tag to the release table"
git -C "$root" push -q -u origin "$branch"
gh pr create -R "$REPO" --base main --head "$branch" \
  --title "docs: add $tag to the release table" \
  --body "Regenerated by scripts/release-table.sh after publishing $tag. Every row's signature was verified against the release key while generating it."
gh pr merge "$branch" -R "$REPO" --auto --squash --delete-branch
git -C "$root" switch -q "$back"
echo "release table PR opened; it merges once CI passes"
